name: Fix lock file

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot-preview[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          persist-credentials: false # minimize exposure
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Regenerate lockfile
        run: |
          yarn

          # deduplicate lockfile
          yarn dedupe
        env:
          YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts
      - name: Commit lockfile
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build(devs-dep): dependabot autofix'

          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          commit_options: '--no-verify --signoff --amend'

          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true

          # Optional: Skip internal call to `git fetch`
          skip_fetch: true
